x-s3-env: &s3-env
  AWS_ACCESS_KEY_ID: admin
  AWS_SECRET_ACCESS_KEY: password
  AWS_REGION: us-east-1
  AWS_DEFAULT_REGION: us-east-1
  S3_ENDPOINT: http://minio:9000
  S3_PATH_STYLE_ACCESS: "true"


services:

  kafka:
    image: apache/kafka:3.9.0
    container_name: kafka
    hostname: kafka

    networks:
      cdc-net:

    ports:
      - "9092:9092"
      - "29092:29092"

    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,PLAINTEXT_HOST://:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

    volumes:
      - kafka-data:/var/lib/kafka/data
      

  postgres:
    image: postgres:15
    container_name: db

    command:
      - postgres
      - -c
      - wal_level=logical
      - -c
      - max_replication_slots=10
      - -c
      - max_wal_senders=10

    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: demo
    ports:
      - "5432:5432"
    networks:
       cdc-net:
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always



  minio:
    image: minio/minio
    hostname: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
      MINIO_DOMAIN: minio
    networks:
      cdc-net:
        aliases:
          - warehouse.minio
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5

    volumes:
      - minio-data:/data


  create-bucket:
    image: minio/mc

    depends_on:
      minio:
        condition: service_healthy

    networks:
      cdc-net:

    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set minio http://minio:9000 admin password)
      do
        echo 'waiting for minio...' && sleep 1;
      done;

      /usr/bin/mc mb minio/warehouse --ignore-existing;
      /usr/bin/mc policy set public minio/warehouse;
      exit 0;
      "


  spark-master:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-master
    networks:
      cdc-net:
    ports:
      - "8080:8080"   # Spark Master web UI
      - "7077:7077"   # Spark Master port
      - "4040:4040"   # Spark application UI
    environment:
      SPARK_MODE: master
      <<: *s3-env

    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    volumes:
      - spark-data:/opt/spark/work-dir

  spark-worker-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-worker-1
    networks:
      cdc-net:
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      <<: *s3-env
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
    volumes:
      - spark-data:/opt/spark/work-dir

  spark-worker-2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-worker-2
    networks:
      cdc-net:
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      <<: *s3-env
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
    volumes:
      - spark-data:/opt/spark/work-dir

  spark-worker-3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-worker-3
    networks:
      cdc-net:
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      <<: *s3-env

    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
    volumes:
      - spark-data:/opt/spark/work-dir


  akhq:
    image: tchiotludo/akhq:0.25.0
    container_name: akhq
    hostname: akhq

    depends_on:
      - kafka

    networks:
      cdc-net:

    ports:
      - "8087:8080"

    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            local-kafka:
              properties:
                bootstrap.servers: "kafka:9092"


  kafka-connect:
    build:
      context: .
      dockerfile: Dockerfile.connect

    container_name: kafka-connect
    hostname: kafka-connect

    depends_on:
      - kafka
      - postgres
    
    networks:
       cdc-net:
    
    ports:
      - "8083:8083"

    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: connect-cluster
      CONNECT_CONFIG_STORAGE_TOPIC: connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: connect-status
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1

      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: false

      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: false

      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect
      CONNECT_PLUGIN_PATH: /usr/share/java,/usr/share/confluent-hub-components

    volumes:
      - connect-data:/data


  duckdb:
    image: ubuntu:24.04
    container_name: duckdb
    networks:
      cdc-net:
    stdin_open: true
    tty: true
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y curl unzip &&
        curl -L https://github.com/duckdb/duckdb/releases/latest/download/duckdb_cli-linux-amd64.zip -o duckdb.zip &&
        unzip duckdb.zip &&
        chmod +x duckdb &&
        mv duckdb /usr/local/bin/duckdb &&
        tail -f /dev/null
      "


networks:
  cdc-net:

volumes:
    postgres-db-volume:
    minio-data:
    spark-data:
    kafka-data:
    connect-data:


 