FROM confluentinc/cp-kafka-connect:7.6.1

USER root

# JDBC connector
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-jdbc:10.7.6

RUN curl -L -o /tmp/debezium.tar.gz \
https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/2.6.1.Final/debezium-connector-postgres-2.6.1.Final-plugin.tar.gz

RUN mkdir -p /usr/share/confluent-hub-components/debezium-postgres \
 && tar -xzf /tmp/debezium.tar.gz -C /usr/share/confluent-hub-components/debezium-postgres \
 && rm -f /tmp/debezium.tar.gz

USER appuser