spring.application.name=gmart


# Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# spring.datasource.url=jdbc:postgresql://localhost:5432/demo
# spring.datasource.username=root
# spring.datasource.password=1234




# Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=DEBUG
